### DISCUSSION TITLE
ReportGenerator for Multiple Projects

### DISCUSSION THREAD

**Discussion by geraldbauer** [danielpalme/ReportGenerator#545] [Q&A]
I have implemented ReportGenerator within our Azure DevOps to gather Code Coverage statistics. We are using Cobertura format. This has been implemented for C# projects and JavaScript projects (aka UI). I now need to aggregate all the projects into one report. Upper management wants to see code coverage for all project.

What is the best approach to collecting all the code coverage statistics for all projects.

**Comment by danielpalme** [comment]
Do you generate the different Cobertura files in one pipeline?
If this is the case, you can pass several files to _ReportGenerator_
```
-reports:project1/Cobertura1.xml;project2/Cobertura2.xml
```

If you have several pipelines for your projects, it get's more difficult.
One approach:
- Each pipelines stores the corresponding Cobertura file at a central location (e.g. Azure BlobStorage).
- An additional pipeline retrieves all Cobertura files and passes them to _ReportGenerator_
- Challenge here is: That the source code of **all projects** must be available on the build agent at the same paths, otherwise _ReportGenerator_ is not able to retrieve the source files

**Reply by geraldbauer** [reply]
We generate Cobertura files in several pipelines. Each pipeline creates it own report.

Please correct me if I miss understand. We should 
1. Store the Cobertura files in a central location for each pipeline that all build agents can access
2. Have a pipeline that retrieves the Cobertura files from the central location

Here is where I am perplexed, we need the source code of all project for ReportGenerator? Does this mean we cannot concatenate the Cobertura files into one report?

**Reply by danielpalme** [reply]
If your only goal is to generate one Cobertura file out of several Cobertura files, then you don't necessarily need the source code.
If you also want to generate one of the [HTML formats](https://github.com/danielpalme/ReportGenerator/wiki/Output-formats#html), then you will need the source code. Otherwise your report will be basically empty (apart from the summary page).

**Reply by geraldbauer** [reply]
Yes, the goal is to have only one Cobertura formatted report. We want to aggregate all the pipeline Cobertura formatted reports into one single report, both summary and detail information. 

The lightbulb went off on why you mentioned the source files. ReportGenerator uses the source files as reference for displaying when drilling down within the report.

**Reply by geraldbauer** [reply]
I foresee an Azure DevOps Widget that summarizes our code coverage results that will reside on a Azure DevOps Dashboard. I am thinking that it will contain the Line coverage section found in the index page (html and htm).

Has anyone else asked about a widget like the one I am discribing?

**Reply by danielpalme** [reply]
I'm not familiar with Azure DevOps widgets.
Is it possible to access the HTML file from within the widget?

I usually publish the output generated by _ReportGenerator_

```yaml
- task: reportgenerator@5
  inputs:
    reports: 'Input.xml'
    targetdir: '$(Build.SourcesDirectory)/coveragereport'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coveragereport/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/coveragereport'
```

With this setup, Azure DevOps includes the coverage report in the build results:
![image](https://user-images.githubusercontent.com/859606/189420133-93f1230e-5ccf-444b-8ce9-59ccad232068.png)
