### DISCUSSION TITLE
error NU1301: Unable to load the service index for source after new release

### DISCUSSION THREAD

**Discussion by rudymiked** [danielpalme/ReportGenerator#547] [Q&A] [answered]
Currently seeing 

"error NU1301: Unable to load the service index for source:

The tool package could not be restored.
Tool 'dotnet-reportgenerator-globaltool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

"

After most recent release, is anyone else seeing this? Failing in my CI/CD pipeline and locally.

**Comment by danielpalme** [comment]
I just tried it myself. I install the tool with 
```
dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.10
```

Then I'm able to execute it with:
```
reportgenerator ...
```

I also tried to use it in an Azure DevOps pipeline, this also works:
```yaml
- task: DotNetCoreCLI@2
  displayName: 'Install ReportGenerator'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global dotnet-reportgenerator-globaltool --version 5.1.10'
```
