### DISCUSSION TITLE
Generate PDF

### DISCUSSION THREAD

**Discussion by DiracSpace** [danielpalme/ReportGenerator#618] [Q&A] [answered]
I just wanted to task if there was a way to generate a PDF from the information produced using the [ReportGenerator](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator) Azure Pipeline extension. I'm using the following configuration:

```yaml
- task: reportgenerator@5
   displayName: 'Generate Latex code coverage reporte'
   inputs:
     reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
     targetdir: '$(Agent.TempDirectory)/Reports'
     reporttypes: HtmlInline_AzurePipelines_Dark
```

**Comment by danielpalme** [comment]
The following task produces a _Latex_ file:

```yaml
- task: reportgenerator@5
   displayName: 'Generate Latex code coverage reporte'
   inputs:
     reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
     targetdir: '$(Agent.TempDirectory)/Reports'
     reporttypes: Latex
```

You could then convert the _Latex_ file to a _PDF_ using [MiKTex](https://miktex.org/).
