### DISCUSSION TITLE
spawn UNKNOWN error on Azure

### DISCUSSION THREAD

**Discussion by albertino87** [danielpalme/ReportGenerator#620] [Q&A]
Hello while running ReportGenerator on azure i get this error:

[command]D:\scratch\agents\DEA-E105051137_01\_work\_tool\dncs\1.0.4\x64\dotnet.exe D:\scratch\agents\DEA-E105051137_01\_work\_tasks\reportgenerator_be803a55-9253-4895-a525-be570d86f161\5.1.24\tools\netcoreapp3.1\ReportGenerator.dll -reports:**/test_reports/*_coverage.xml -targetdir:CoverageResults -reporttypes:Cobertura -sourcedirs: -historydir: -plugins: -assemblyfilters:+* -classfilters:+* -filefilters:+* -verbosity:Info -title: -tag:20230823.3_#39723 -license:
##[error]spawn UNKNOWN
##[section]Finishing: Merge coverage results

Can somebody help me?

The step in the pipeline looks like this:
```
      - task: reportgenerator@5
        displayName: 'Merge Code Coverage Results'
        inputs:
          reports: '**/test_reports/*_coverage.xml'
          targetdir: 'CoverageResults'
          reporttypes: Cobertura
```
