### DISCUSSION TITLE
How do I ignore an entire directory of files or namespace of files?

### DISCUSSION THREAD

**Discussion by BenjaminMichaelis** [danielpalme/ReportGenerator#648] [Q&A] [answered]
I have a directory under my `.sln` that is called `Migrations` that I want to ignore the whole directory of files of, or I have the namespace as `Foo.Thing.Migrations`. 

I am currently doing the following in my actions:

```yaml
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: coveragereport
          reporttypes: MarkdownSummaryGithub
          classfilters: Foo.Thing.Migrations
          filefilters: "*Migrations*"
```

but in the summary markdown it still includes the output from that directory in the calculations:

## Coverage
<details><summary>Foo.Thing- 0%</summary>

| Name | Line |
|--------|--------|
| Foo.Thing.Migrations.AddThing | 0% |
| Foo.Thing.Migrations.RemoveThing |  0% | 
</details>

How do I avoid this from being included?

**Comment by danielpalme** [comment, marked as answer]
@BenjaminMichaelis 
You are missing a little detail in your filters. They need to start with a "+" or "-".

This should work:
```yml
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: coveragereport
          reporttypes: MarkdownSummaryGithub
          classfilters: -Foo.Thing.Migrations
          filefilters: "-*Migrations*"
```
 
See also: https://reportgenerator.io/usage
