### ISSUE TITLE
A dark theme support

### ISSUE THREAD

**Issue by moikot** [danielpalme/ReportGenerator#203]
ReportGeneraor is a nice tool and helps me a lot but I'm using a dark theme in Azure Devops and it would be nice to have dark theme support in the generator too.

**Comment by danielpalme** [comment]
Will add support for this in the next days.

**Comment by danielpalme** [comment]
I assume you are using the [Azure DevOps extension](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator)?

I just published an update (version 1.0.19). It should be available within the next minutes.

If you want to use the dark theme, you have to change the setting "Report types" from `HtmlInline_AzurePipelines` to `HtmlInline_AzurePipelines_Dark` 

![image](https://user-images.githubusercontent.com/859606/51790158-e0fa8600-2191-11e9-8dfc-f47d229dbd7a.png)

Or in your YAML file:
```YML
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@1
  displayName: ReportGenerator
  inputs:
    reports: 'src\target\reports\coverage\coverage.opencover.xml'
    targetdir: 'src\target\reports\coverage'
    reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura'
```

Does this work for you?
