### ISSUE TITLE
Issue with report generator Ubuntu

### ISSUE THREAD

**Issue by ThomasBDO** [danielpalme/ReportGenerator#222]
I have an issue making reports in the Azure Pipeline with the report generator, where I get the error: 
**No executable found matching command "dotnet-reportgenerator**

From my Azure-Pipelines.yaml

```
pool:
  vmImage: 'Ubuntu-16.04'

# Run unit tests
- task: DotNetCoreCLI@2
  displayName: 'Running unit tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger "trx;LogFileName=testresults.trx"'

# Run code coverage
- task: DotNetCoreCLI@2
  displayName: 'Running code coverage'
  inputs: 
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(System.DefaultWorkingDirectory)/TestResults/Coverage/'

# Create report
- task: DotNetCoreCLI@2
  displayName: "Generating code coverage Reports"
  inputs:
    projects: '**/*Tests/*.csproj'
    command: custom
    custom: reportgenerator
    arguments: "-reports:$(System.DefaultWorkingDirectory)/TestResults/Coverage/*.xml -targetdir:results -reporttypes:HTMLInline;HTMLChart"
```

In my .csproj for the test-project, I have:

```
<ItemGroup>
    <DotNetCliToolReference Include="dotnet-reportgenerator-cli" Version="4.0.15" />
```

I have also reported the error here:
https://github.com/Microsoft/azure-pipelines-tasks/issues/9472
