### ISSUE TITLE
Q: Where does $(Parameters.TestProjects) get set in your build pipeline?

### ISSUE THREAD

**Issue by ardalis** [danielpalme/ReportGenerator#264]
I'm trying to borrow from your working code in your azure-pipelines.yml but when I used this:
```
# Run tests and create coverage report
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    projects: '**/*[Tt]ests/*.csproj'
```
I got no test projects matching the pattern.

When I use this, it finds my test project(s):
```
# Run tests and create coverage report
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
```

Is $(Parameters.TestProjects) something you're setting outside of the pipeline file, I assume, perhaps as a build agent environment variable? Thanks
