### ISSUE TITLE
Does not install for .Net Core 3.1

### ISSUE THREAD

**Issue by hlubovac** [danielpalme/ReportGenerator#317]
I tried both of these:

```
dotnet tool install -g dotnet-reportgenerator-globaltool
dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
```

But I keep getting this:

```
error NU1100: Unable to resolve 'dotnet-reportgenerator-globaltool ' for '.NETCoreApp,Version=v3.1'.
error NU1100: Unable to resolve 'dotnet-reportgenerator-globaltool ' for '.NETCoreApp,Version=v3.1/any'.
The tool package could not be restored.
Tool 'dotnet-reportgenerator-globaltool' failed to install.
```

Is there something I am missing?
Thank you.

**Comment by danielpalme** [comment]
I tried this on my machine and it just works fine.
Hard to guess what's different on your machine.

What's the output of `dotnet --info` on your machine?

**Comment by hlubovac** [comment]
Thanks.

So, the context (which I failed to mention) is Azure DevOps Pipelines, and the base-image is "ubuntu:latest", with .Net Core 3.1.101 installed on top of it (so, `dotnet-reportgenerator-globaltool` wouldn't install on _that_ system).

At some point it occurred to me to suspect whether this tool is even made to run on non-Windows, then I stumbled upon [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops) - which worked for me, and then I ended up not using your library (sorry).

But, to answer your question, the output of `dotnet --info` in the mentioned environment is this:
```
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/59652352-eaf5-41fd-9d87-f1e376dbf7c0.sh
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /opt/hostedtoolcache/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/opt/hostedtoolcache/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/opt/hostedtoolcache/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by hlubovac** [comment]
... but, if you have suggestions how to make ReportGenerator work on the platform that I described - I'd be grateful: I just discovered that the pipelines-task that I linked to does not support multiple Cobertura files (and adding the same task multiple times doesn't work properly), while ReportGenerator is capable of merging those xml files into one (however, I'm again stuck at the setup step). Thanks!

**Comment by hlubovac** [comment]
This guy just offset this multi-file problem on you: https://github.com/Microsoft/azure-pipelines-tasks/issues/8707

**Comment by danielpalme** [comment]
I created a Ubuntu virtual machine and installed .NET Core SDK 3.1.
On this machine the output of `dotnet --info` is:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

That looks very similar to your output.
Then I executed the following command `dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools`.
The installation went successfully and I was able to execute ReportGenerator with `tools/reportgenerator`.

I have not tried this with an _Azure DevOps_ build agent yet.
But since you are using _Azure DevOps_, you could also try the [Azure DevOps extension](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator) of _ReportGenerator_.

**Comment by hlubovac** [comment]
Thank you very much for spending time to troubleshoot. In the end, this combination below worked for me - so, it suddenly started working (I must have had something wrong). The last two tasks are the most relevant, while the disabled `reportgenerator` statement there does execute, but it does not integrate in Azure Pipelines in such a way that it would display the produced HTML report (image below) - so, I ended up using a built-in task, which seems to properly set up this tool.

```
pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "./src/Service.sln"
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      displayName: "Install .NET Core"
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
    - task: DotNetCoreCLI@2
      displayName: "Compile VS solution"
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration "$(buildConfiguration)" --source "https://$(myget-org).myget.org/F/dasdevelopment/auth/$(myget-apikey)/api/v3/index.json" --source "https://api.nuget.org/v3/index.json"'
    - task: DotNetCoreCLI@2
      displayName: "Execute unit tests and calculate code-coverage"
      inputs:
        command: 'test'
        projects: '$(solution)'
        arguments: '--filter "Category!=IntegrationTest" "-p:CollectCoverage=true" "-p:CoverletOutputFormat=cobertura"'
        nobuild: true
    - task: CmdLine@2
      displayName: Merge code-coverage files
      inputs:
        script: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator "-reports:./src/**/coverage.cobertura.xml" "-reporttypes:Cobertura" "-targetdir:./coverreport"
        # reportgenerator "-reports:./coverreport/Cobertura.xml" "-reporttypes:Html" "-targetdir:./coverreport"
    - task: PublishCodeCoverageResults@1
      displayName: "Generate code-coverage HTML report"
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: './coverreport/Cobertura.xml'
        failIfCoverageEmpty: true
```

![image](https://user-images.githubusercontent.com/3127736/73472286-0a6f6400-4348-11ea-87e2-e7771c32628d.png)

Thank you very much for the great utility. I will ask my employer to kick back.
