### ISSUE TITLE
Error rendering Badge report in Azure Devops hosted Ubuntu agent

### ISSUE THREAD

**Issue by eduherminio** [danielpalme/ReportGenerator#342]
Task:

```yaml
    - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
      displayName: 'Generate tests report'
      condition: eq(variables['imageName'], 'ubuntu-latest')
      inputs:
        reports: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
        targetdir: '$(CoverageResults)'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
        assemblyfilters: '-xunit*'
```

Generate log using `ubuntu-latest`:
`Error during rendering summary report (Report type: 'Badges'): Font 'Arial' is not available. Therefore only SVG badges can be generated. PNG files are omitted.`

[Complete log](https://dev.azure.com/eduherminio/SheepTools/_build/results?buildId=317&view=logs&j=b4c15bfd-ed3a-51d0-c6ff-5db20342b7d5&t=9853c838-2717-56bf-2348-9393ed9de52d)
