### ISSUE TITLE
Add Azure Devops pipeline example

### ISSUE THREAD

**Issue by nilshedstrom** [danielpalme/ReportGenerator#344]
If you are using Azure Devops and want to use history function you do not have to write a custom plugin for history storage.
Instead you can store the history files in Azure Artifacts as Universal Packages. 
So the build pipeline is something like this
* Get the previous history from Azure Artifacts
* Generate the report and new history
* Put the new history to Azure Artifacts

This is a part of my Azure Pipeline

```
variables:
  disable.coverage.autogenerate: 'true'
  codecoveragehistory.directory: '$(Build.ArtifactStagingDirectory)\history'
  codecoveragehistory.feedName: '$(Build.Repository.Name)-$(Build.SourceBranchName)'
```
```
- task: UniversalPackages@0
  displayName: Get code coverage history from Azure Artifacts
  continueOnError: true
  inputs:
    command: 'download'
    downloadDirectory: '$(codecoveragehistory.directory)'
    feedsToUse: 'internal'
    vstsFeed: 'xxxxxxx'
    vstsFeedPackage: '$(codecoveragehistory.feedName)'
    vstsPackageVersion: '0.*'
    
- task: reportgenerator@4
  displayName: 'Create Code coverage report'
  inputs:
    reports: '$(Build.SourcesDirectory)\**\coverage.cobertura.xml'
    targetdir: '$(Build.SourcesDirectory)\CodeCoverage'
    historydir: '$(codecoveragehistory.directory)'
    title: 'Merged code coverage for $(Build.Repository.Name)-$(Build.SourceBranchName)'

- task: UniversalPackages@0
  displayName: Publish code coverage history to Azure Artifacts
  inputs:
    command: 'publish'
    publishDirectory: '$(codecoveragehistory.directory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'xxxxxx'
    vstsFeedPackagePublish: '$(codecoveragehistory.feedName)'
    versionOption: 'patch'
    packagePublishDescription: 'Code Coverage History for repository $(Build.Repository.Name) on branch $(Build.SourceBranchName)'
    verbosity: 'Information'
```
