### ISSUE TITLE
Command not find on Azure Pipelines

### ISSUE THREAD

**Issue by programad** [danielpalme/ReportGenerator#354]
Hey, man, thank you for your awesome tool but I am facing a weird bug.

Some reports gets generated like badges and azurehtml, others i receive "command not found" like Cobertura, HTMLInline and HTMLChart.

![image](https://user-images.githubusercontent.com/1039567/85089578-5cab0780-b1b9-11ea-9548-a489fd43bfe2.png)

I am using the following yml code:

```yml
- task: DotNetCoreCLI@2
  displayName: 'Install ReportGenerator tool'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global dotnet-reportgenerator-globaltool'

- script: reportgenerator "-reports:$(Build.SourcesDirectory)/**/coverage.opencover.xml" "-targetDir:$(Build.SourcesDirectory)/CodeCoverage" -tag:$(Build.BuildNumber) -reportTypes:Badges;Cobertura;HTMLInline;HTMLChart
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Run Report Generator'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
```

I tried several combinations with no success.

Any ideas on what is causing this?

**Comment by danielpalme** [comment]
I guess that you have to add quotes around the `-reporttypes`:

```yaml
- script: reportgenerator "-reports:$(Build.SourcesDirectory)/**/coverage.opencover.xml" "-targetDir:$(Build.SourcesDirectory)/CodeCoverage" -tag:$(Build.BuildNumber) "-reportTypes:Badges;Cobertura;HTMLInline;HTMLChart"
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Run Report Generator'
```
