### ISSUE TITLE
Error during reading report 'clover.xml' (Size: 171.3KB): An item with the same key has already been added.

### ISSUE THREAD

**Issue by maisreymom** [danielpalme/ReportGenerator#363]
I have generated code coverage report using clover, and then try to run reportgenerator to generate report and I got this error. Do you have any idea about this?

Actually I do the same thing with my other projects, and it working fine.

**Comment by danielpalme** [comment]
Can you share your coverage file?

**Comment by maisreymom** [comment]
Thank you so much but I am sorry I couldn't share it with you.

**Comment by danielpalme** [comment]
Thanks for your email. Will have a look as soon as possible.

**Comment by danielpalme** [comment]
New release 4.6.2 fixes this issue.

**Comment by maisreymom** [comment]
Thanks @danielpalme

**Comment by MikaelFerland** [comment]
@danielpalme, I have the same kind of issue with opencover.xml.

**Comment by danielpalme** [comment]
Will have a look at the end of august

**Comment by danielpalme** [comment]
@MikaelFerland 
Can you share a sample OpenCover file?
You don't have to share it here in public. You can also send it by email: danielpalme82@gmail.com

**Comment by danielpalme** [comment]
@MikaelFerland:
Thanks for sharing your OpenCover file.

The file seems to be "invalid". It contains `<TrackedMethod />` elements. Each element should have a unique `uid` attribute. This is not the case with this file.

Which tool are you using to generate the file (e.g. [OpenCover](https://github.com/OpenCover/opencover), [coverlet](https://github.com/coverlet-coverage/coverlet/), [altcover](https://github.com/SteveGilham/altcover))?

**Comment by MikaelFerland** [comment]
I'm using OpenCover.

**Comment by danielpalme** [comment]
I guess that OpenCover is no longer actively maintained (@sawilde?!)
But at least ReportGenerator can handle your files now.

**Comment by jason-e-gross** [comment]
I'm getting the same thing when using coverlet on the test runner, with output format `cobertuna `-- and -- when i specify a report type.  

If I leave off specifying a report type ( `reportypes`), it works.

**Comment by danielpalme** [comment]
@jason-e-gross 
Please use the following YAML for light theme:
```yaml
          - task: reportgenerator@4
            inputs:
              reports: '$(Pipeline.Workspace)/testresults/coverage/*.cobertura.xml'
              targetdir: '$(Build.SourcesDirectory)/CoverageResults'
              sourcedirs: '$(System.DefaultWorkingDirectory)/PipelineRuns'
              reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
```

Or this for a dark theme:
```yaml
          - task: reportgenerator@4
            inputs:
              reports: '$(Pipeline.Workspace)/testresults/coverage/*.cobertura.xml'
              targetdir: '$(Build.SourcesDirectory)/CoverageResults'
              sourcedirs: '$(System.DefaultWorkingDirectory)/PipelineRuns'
              reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura'
```

Specifying several HTML report types is not useful. You will get an unpredictable result!
