### ISSUE TITLE
Mismatch between Branch Coverage in Cobertura and HTML reports

### ISSUE THREAD

**Issue by ardalis** [danielpalme/ReportGenerator#393]
We are generating code coverage using `dotnet test`, coverlet, and cobertura. We are using ReportGenerator to combine the coverage results and generate both Cobertura and HTML reports. We are also integrating with Build Quality Checks to gate the builds if line or branch coverage dips below a certain threshold.

We would very much like for the HTML reports to show the same numbers that the build gates will trigger off of. It's obviously very confusing to see a build fail because branch coverage is too low, but look at the Code Coverage tab and see that it's clearly above the require threshold.

I know this is related to other issues that have been closed related to how RG counts branches vs. how cobertura does. However, since RG is responsible for generating the combined cobertura.xml file, couldn't it use its own count when generating the coverage element in that file so that it matches the HTML output?

See related issue here with screenshots and more details: 
https://github.com/MicrosoftPremier/VstsExtensions/issues/120

Thanks!

**Comment by ardalis** [comment]
Here's how we're combining the coverage files from 3 different test runs:

```
    - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
      displayName: Test Code Coverage Report Generator
      inputs:
        reports: '$(Build.SourcesDirectory)/tests/{unittests}/coverage.cobertura.xml;$(Build.SourcesDirectory)/tests/{integrationtests}/coverage.cobertura.xml;$(Build.SourcesDirectory)/tests/{functionaltests}/coverage.cobertura.xml;'
        targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
        assemblyfilters: '-xunit*'  
```

**Comment by danielpalme** [comment]
The HTML and the Cobertura file generated by ReportGenerator should be consistent.
Before we have a look at the concrete files, let's make sure that the problem is not related to Azure Devops.

You are using the "PublishCodeCoverageResults" task:
```yaml
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
        reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
``` 

This task uses the Coberatura file generated by ReportGenerator but it does not use the HTML output of ReportGenerator.
Instead it regenerates the HTML report based on the Coberatura file.
To disable that behavior, you have to set an environment variable:
```yaml
disable.coverage.autogenerate: 'true'
```

See also: https://github.com/danielpalme/ReportGenerator/wiki/Integration#attention

Does this fix your problem?

It might be helpful to pack the output of ReportGenerator (directory $(Build.SourcesDirectory)/CodeCoverage) into an artifact which you can download. Then you can inspect the HTML and Cobertura files directly.
