### ISSUE TITLE
Ignore absence of coverage input

### ISSUE THREAD

**Issue by buckleyGI** [danielpalme/ReportGenerator#404]
**Describe the bug**

I have the ReportGenerator azure devops extension running in a generic yaml template.
Sometimes the pipeline that uses the generic template has a test project, sometimes it has not.
As a result is sometimes has coverage and sometimes not.

```
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: ReportGenerator
  inputs:
    reports: '**\coverage.cobertura.xml'
    targetdir: 'ReportGenerator'
```
I specify the required reports key as '**\coverage.cobertura.xml'

When I run the pipeline I get this error

```
2021-01-15T09:17:55: The report file pattern '**\coverage.cobertura.xml' is invalid. No matching files found.
2021-01-15T09:17:55: No report files specified
```
I looked for a setting such as `failIfCoverageEmpty: true/false` which the MS PublishCodeCoverageResults task has for example.

I am writing some custom script to conditionally skip the ReportGenerator (challenge: support globbing patterns) so I have a workaround.

Is there such a setting for ReportGenerator? I read the docu and issues here but could not find it.

Thank you, Tom
