### ISSUE TITLE
Code coverage missing in solution project

### ISSUE THREAD

**Issue by Beelzenef** [danielpalme/ReportGenerator#412]
I have been using this tool for a few days, as I am working to increase the code coverage of my project.

The problem is, if I check the code coverage from Visual Studio, this is the result:

![image](https://user-images.githubusercontent.com/6389665/112999639-68c3ec80-916f-11eb-88db-08ff1db542f5.png)

On the other hand, when executing the code coverage with ReportGenerator, it does not detect the tests of other projects that do have tests.

![image](https://user-images.githubusercontent.com/6389665/113001345-01a73780-9171-11eb-96f2-f8d59ddb185c.png)

As you can see, the TaleEngine.Application project should have some code coverage percentage, as there are quite a few tests on its files... however, it shows 0%. In both captures, I am using the same branch, same commit.

The NuGet package coverlet.msbuild is installed in all test projects, and this is the CI pipeline: 

```yaml
pool:
  name: Azure Pipelines
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Testing/*.csproj'
    arguments: '--configuration $(BuildConfiguration)  /p:CollectCoverage=true  /p:CoverletOutputFormat=cobertura   /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\Coverage\'

- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: ReportGenerator
  inputs:
    reports: '$(Build.SourcesDirectory)/TestResults/Coverage/*cobertura.xml'
    targetdir: '$(Build.SourcesDirectory)/TestResults/Coverage'
    sourcedirs: '$(Build.SourcesDirectory)'
    historydir: '$(Build.SourcesDirectory)/TestResults/History'
    assemblyfilters: '-xunit*'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/Coverage/*cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/TestResults/Coverage'
```

What am I doing wrong? What can be missing from in pipeline definition?

Thanks for your time, cheers!
