### ISSUE TITLE
Markdown report

### ISSUE THREAD

**Issue by mifriis** [danielpalme/ReportGenerator#431]
Hi Daniel and co.

What a great package! It helped me integrate coverage into our review phase by coupling it with a github action that creates a comment on the PR with the artifact.

```YAML
    - name: Test      
      run: |
        dotnet test --no-restore --no-build --configuration $config --collect:"XPlat Code Coverage"
        dotnet ~/.nuget/packages/reportgenerator/4.8.9/tools/netcoreapp3.0/ReportGenerator.dll "-reports:**/coverage.cobertura.xml;" "-targetdir:${{github.workspace}}/report" "-reporttypes:Html;TextSummary"
      
    - name: Upload reports
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Test Run'
        path: |
          ${{github.workspace}}/report
      
    - name: Comments on PR with coverage report results
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: Coverage Report
        path: ${{github.workspace}}/report/Summary.txt
```

One improvement I am looking to make, is to make the comment a bit more inviting to read. I use the TextSummary report today, which tends to be a bit "boring" as a comment. Something like markdown would make it possible to use tables and icons to aid the reader. 

Can you help?

I looked a bit into the custom reports, but before i dive too deep into it, perhaps someone from the community already built one or markdown support is planned for a future release. Even a link to a repo with a custom rapport would be of interest.
