### ISSUE TITLE
LCOV report type empty when using C# code coverage JSON file

### ISSUE THREAD

**Issue by CalvinWilkinson** [danielpalme/ReportGenerator#435]
**Describe the bug**
I am currently having an issue where the produced **lcov.info** file is empty.  The only content it has in it is a single line of text at the top that is **TN**.

I have a **NET 5.0** library that I am running tests for using **GitHub actions**.  Once the tests produce the coverage result in **lcov** format, I am pointing the **reportgenerator** to the produced **coverage.json** file created with the tests from the previous step.

I am trying to use the **coverallsapp v1.1.2** GitHub action to pick up the **lcov.info** file and that is when **coveralls** reports back to me that it cannot parse the string.  Upon investigation, revealed that the **lcov.info** file was empty.

**coveralls error:**
![image](https://user-images.githubusercontent.com/85414302/124112180-06ada880-da38-11eb-83a6-6f7321be6562.png)

**This is the unit testing section of my YAML**
``` yaml
  Run_Unit_Tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Execute Unit Tests
        run: dotnet test "${{ github.workspace }}\\Testing\\CASLTests\\CASLTests.csproj" -c Debug-WIN /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOuputFormat=lcov
      
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.11
        with:
          reports: "**/TestResults/coverage.json"
          targetdir: "${{ github.workspace }}\\Testing\\CASLTests\\TestResults"
          reporttypes: lcov

      - name: Publish Code Coverage Results
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          path-to-lcov: "${{ github.workspace }}\\Testing\\CASLTests\\TestResults\\lcov.info"
```

**To Reproduce**
1. Console output of ReportGenerator
![image](https://user-images.githubusercontent.com/85414302/124112621-791e8880-da38-11eb-9081-d0a91801e089.png)

2. Here is a zip with 2 files in it.  The **coverage.json** files is the file produced by the **dotnet cli**.  Of course the **lcov.info** file is produced by the report generator.
[GeneratedCoverageFiles.zip](https://github.com/danielpalme/ReportGenerator/files/6747575/GeneratedCoverageFiles.zip)

To reproduce this, I simply ran the same commands that is being performed in the **YAML** file.

**Comment by danielpalme** [comment]
ReportGenerator can't handle the JSON format generated by coverlet, you can use _OpenCover_ or _Coberatura_ format instead. 
See: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#coverage-output  

If you adjust your action, it should work:

```yaml
      - name: Execute Unit Tests
        run: dotnet test "${{ github.workspace }}\\Testing\\CASLTests\\CASLTests.csproj" -c Debug-WIN /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOuputFormat=cobertura
      
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.11
        with:
          reports: "**/TestResults/coverage.cobertura.xml"
          targetdir: "${{ github.workspace }}\\Testing\\CASLTests\\TestResults"
          reporttypes: lcov
```
