### ISSUE TITLE
Does not show badge

### ISSUE THREAD

**Issue by RachelXGanon** [danielpalme/ReportGenerator#453]
Hi,
I used the action `danielpalme/ReportGenerator`  GitHub-Action,
I told him to display those options:
```
 - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.12
        with:
            reporttypes: 'Badges;Clover;Cobertura;CsvSummary;Html;HtmlChart;HtmlInline;HtmlSummary;JsonSummary;Latex;LatexSummary;lcov;MarkdownSummary;MHtml;PngChart;SonarQube'
```

but I don't see any badges. only I get a folder contains all those outputs.
I need the badges to be displayed for the Code Review.
What did I do wrong?
Thank you.
