### ISSUE TITLE
Report within Azure DevOps Code Coverage tab doesn't load js/external files even with type HtmlInline_AzurePipelines

### ISSUE THREAD

**Issue by hjdarnel** [danielpalme/ReportGenerator#460]
**Describe the bug**
When I run the dotnet global tool in my build pipeline, then publish the `HtmlInline_AzurePipelines` report, the resulting display in the Code Coverage tab of the build doesn't appear quite right - for example, missing the ability to "fold" a group of coverage, filter, and the "Sponsor" and "Star" icons are missing.

I can make it appear the same if I build the report locally, then using the browser debugger, disable JavaScript and block the data url network requests for the icons.

I don't necessarily think it's a bug, perhaps a way that I'm using the tool.

**To Reproduce**
My pipeline looks as such (with extraneous steps removed):
```yaml
variables:
  buildConfiguration: 'Release'
  disable.coverage.autogenerate: 'true'

trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: DotNetCoreCLI@2
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    feedsToUse: config

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/My.Test.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    publishTestResults: true

- script: dotnet reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:'Cobertura;HtmlInline_AzurePipelines'
  displayName: Create code coverage html report

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage html report'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
```

Please let me know if I can be any clearer. Attached is a screenshot of the output. Thank you for your time and the amazing tool. 

![image](https://user-images.githubusercontent.com/7868899/139166144-afd7f9e5-f9ed-443b-8d51-8f2766cbf6bb.png)
