### ISSUE TITLE
Source code files missing in the Overall code coverage report ->  Maven Jacoco xml reports merged, converted to Cobertura xml

### ISSUE THREAD

**Issue by msrinivascharan** [danielpalme/ReportGenerator#480]
Hi Team..

I have two Java modules in my app, generating code coverage reports in xml format for both using Maven Jacoco plugin.

**Azure DevOps YML pipeline:** 

1. Job1 in Azure DevOps pipeline uploads two (modules) jacoco.xml files to azure pipeline as artifact.

2. Job1 in Azure DevOps pipeline uploads two (modules) source code to azure pipeline as artifact.

3. Job2 in Azure DevOps pipeline downloads jacoco.xml files and source code

4. Job2 in Azure DevOps pipeline merges two jacoco xml’s into one, and convert it into Cobertura format (Cobertura.xml)

5. Job2 in Azure DevOps pipeline publish the Overall coverage report( Cobertura.xml )

**Issue:** 

Build’s Overall code coverage report (Code coverage tab in build summary) showing wrong data. At package level, though metrics like covered un covered lines etc appearing, when clicked on package hyperlink, source code files missing, showing less number of files or completely blank.

Please help, waiting  for your inputs.

**Comment by danielpalme** [comment]
Hi @msrinivascharan 

without further details, it's very hard to tell what's wrong with your setup.
The following reasons may apply here:

- In step 4. your are merging the Jacoco files into a Cobertura file. I guess you are using _ReportGenerator_ for this? You could replace this with generating the HTML report from the Jacoco files instead of merging.
- In step 5 you are publishing the report (is guess you are using _PublishCodeCoverageResults@1_ for that?). This task regenerates the coverage report based on the Coberatura file if you don't set `disable.coverage.autogenerate: 'true'`.

The following setup for Job 2 should work for you:

```yaml
variables:
  disable.coverage.autogenerate: 'true'

- task: reportgenerator@5
  displayName: ReportGenerator
  inputs:
    reports: 'jacoco1.xml;jacoco2.xml'
    targetdir: 'coveragereport'
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
    sourcedirs: 'TODO'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(build.sourcesdirectory)\coveragereport\Cobertura.xml'
    reportDirectory: '$(build.sourcesdirectory)\coveragereport'
```

If _ReportGenerator_ is not able to find the source files, you should provide the base directory/directories with the `sourcedirs` parameter.
