### ISSUE TITLE
Workflow Defaults working-directory is not used

### ISSUE THREAD

**Issue by YounesCheikh** [danielpalme/ReportGenerator#492]
I'm using Github Action to run tests then generate a report for test coverage. In my GitHub workflow file I set a [defaults](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun) to set the working directory as the source code is not in repository root but in a directory named src : 
```yaml
defaults:
  run:
    working-directory: src
```
The working-directory is well used when building and testing, however, the report generator is running on root directory. 
Currently I'm using the absolute path `reports` option. 
```yaml
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.4
      with:
        reports: './src/TestResults/coverage.cobertura.xml' 
```

The solution above works fine. but I guess it will be much better to use the global working-directory as set in the action to switch automatically the working directory when running report generator, then the user just set the relative path to the `reports` option. 

**Live example**
Actually, the problem described above got it when building the action at [dotnet.yml file]( https://github.com/YounesCheikh/Cliargs.NET/blob/94b5d8ff59c6968fe3e7a0d5aa7bbacf2bdf61f1/.github/workflows/dotnet.yml#L32) on Github repository.
