### ISSUE TITLE
Fails to display source file contents when used with SourceLink and private AzureDevOps repo.

### ISSUE THREAD

**Issue by VanessaRussell** [danielpalme/ReportGenerator#501]
Like #443, Report Generator is failing to render the source file contents for my new .NET 6 NuGet packages.

Sample Output:
![image](https://user-images.githubusercontent.com/86689712/158913580-c7bd8bfb-18af-47fd-ac4b-7ccec1ebdec4.png)

Relevant .yml .csproj .props .targets files
[Relevant Files.zip](https://github.com/danielpalme/ReportGenerator/files/8295421/Relevant.Files.zip)

The pipeline and the repo are a part of the same Azure DevOps project.  The pipeline also has access to the repo when pulling down the source code.  Likewise, I have access to the url shown in the output if I open it up in a new tab.  Therefore, I don't fully understand why it's rendering the sign in html rather than the actual file.

**Comment by danielpalme** [comment]
Will have a look within the next days.

**Comment by danielpalme** [comment]
ReportGenerator just get's the path of the file. Since it starts with "https://", it's not a local file which is present on the build agent.
Therefore ReportGenerator tries to download the file.
You can view and download the file in your browser since you are authenticated, but ReportGenerator is a command line tool which is not authenticated.

To allow ReportGenerator access your files, you can do the following:

1) Generate a "Personal access token" here: https://dev.azure.com/<YOUR_NAME>/_usersSettings/tokens 

![image](https://user-images.githubusercontent.com/859606/159122220-5d592a57-b2c9-492b-86d0-8e8de1864f4f.png)

2) Copy the token and convert it to base64 format:
https://www.base64encode.org
Before conversion you have to prepend a ":".

Example for token "xyz":

`xyz` -> `:xyz` -> `Onh5eg==`

3) Add the following to your Azure Devops pipeline

```yml
- task: reportgenerator@5
      displayName: ReportGenerator
      inputs:
        reports: 'coverage.xml'
        targetdir: 'coveragereport'
        customSettings: 'settings:customHeadersForRemoteFiles=Authorization=Basic Onh5eg=='
```

The last line is the important one. Here you are passing the personal access token.

Does this help?

**Comment by VanessaRussell** [comment]
Hi @danielpalme,

I unfortunately cannot use the pipeline task.  As such, I've been using the exe in a script like this:
``` yaml
      - task: PowerShell@2
        displayName: Generate Coverage Report
        inputs:
          targetType: inline
          script: |
            $(ReportGeneratorPath) "-reports:$(TestResultsPath)/VssAdmin*/**/coverage.opencover*.xml" "-targetdir:$(TestCoverageReportPath)" "-reporttypes:Cobertura;HtmlInline"
```

Looking at the README of this project, I can't seem to find how to pass the PAT in via the command line

**Comment by danielpalme** [comment]
On the command line you can use:
```yml
      - task: PowerShell@2
        displayName: Generate Coverage Report
        inputs:
          targetType: inline
          script: |
            $(ReportGeneratorPath) "-reports:$(TestResultsPath)/VssAdmin*/**/coverage.opencover*.xml" "-targetdir:$(TestCoverageReportPath)" "-reporttypes:Cobertura;HtmlInline settings:customHeadersForRemoteFiles=Authorization=Basic Onh5eg=="
```

See also: https://github.com/danielpalme/ReportGenerator/wiki/Settings
