### ISSUE TITLE
Enhancement: support reportgenerator integration with gitlab

### ISSUE THREAD

**Issue by mcallaghan-geotab** [danielpalme/ReportGenerator#513]
**General Inquiry**
Looks like this tool supports a myriad of existing CI/CD tools (https://github.com/danielpalme/ReportGenerator/wiki/Integration) Neat!
Might there be a plan/chance to add integration support for gitlab?

**Comment by mcallaghan-geotab** [comment]
Wow very nice @danielpalme  Thanks!  Worth inclusion on your integration wiki?

**Comment by mcallaghan-geotab** [comment]
@danielpalme  - uhoh? 

https://gitlab.com/gitlab-org/gitlab/-/issues/17633
https://docs.gitlab.com/ee/ci/pipelines/settings.html#add-test-coverage-results-using-project-settings-removed

did gitlab just remove support for this?

**Comment by danielpalme** [comment]
Seem to be removed, but there is a new option:
https://docs.gitlab.com/ee/ci/yaml/index.html#coverage

**Comment by mcallaghan-geotab** [comment]
Ah yes, that method is the "usual way" we're used to capturing coverage from a job. It isn't clear though from documentation how `##teamcity\[buildStatisticValue key=\'CodeCoverageS\' value='(\d+\.?\d*)'\]` should be "inserted" to `coverage:`; verbatim? (I've never seen this `##teamcity` prefix.

**Comment by danielpalme** [comment]
This should work:

```yml
stages:
  - build
  - test

build_job:
  stage: build
  script:
    - 'cd src'
    - 'dotnet restore --packages .nuget'
    - 'dotnet publish -c Release .\MyProject\MyProject.csproj'

test_job:
  stage: test
  script:
    - 'cd src'
    - 'mkdir coveragereports'
    - 'dotnet test -c Release --collect:"XPlat Code Coverage"'
    - '.\.nuget\reportgenerator\5.1.4\tools\net6.0\ReportGenerator.exe -reports:MyProject.Test\TestResults\*\coverage.cobertura.xml -targetdir:coveragereports "-reporttypes:Html;TeamCitySummary" -verbosity:Info -historydir:coveragehistory'
  coverage: '/##teamcity\[buildStatisticValue key=\'CodeCoverageS\' value='(\d+\.?\d*)'\]/'
  artifacts:
    paths:
      - '.\src\coveragereports'
  dependencies:
    - build_job
```
