### ISSUE TITLE
Help me to show data on Code Coverage tab

### ISSUE THREAD

**Issue by dima104** [danielpalme/ReportGenerator#559]
I'm running my build pipeline and in Code Coverage tab I can only download the result, but I want to see it instead.

my last 2 tasks which are responsible for Code Coverage are looking like this:

```
-task: reportgenerator@4
 displayName: ReportGenerator
 inputs:
   reports: 'Project/BuildScripts/OpenCover.xml'
   targetdir: 'coveragereport'
   sourcedirs: '$(System.DefaultWorkingDirectory)'
   filefilters: '-*fluentvalidation*;-*Humanizer*;-*moq*;-*Project.Test*;-*Pipelines*;-*xunit*'
 enabled: true

-task: PublishCodeCoverageResults@1
 displayName: 'Publish code coverage from coveragereport\Cobertura.xml'
 inputs: 
   codeCoverageTool: Cobertura
   summaryFileLocation:  'coveragereport\Cobertura.xml'
 enabled: true
```

I already tried to change version of reportgenerator to reportgenerator@5 and even remove filefilters, but nothing helps. 

Maybe the problem is with different task?

What can I add/do in order to display Code Coverage results in Code Coverage tab?

**Comment by danielpalme** [comment]
Please use the following YAML for `PublishCodeCoverageResults` (you are missing the `reportDirectory` property):

```yaml
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from coveragereport\Cobertura.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation:  'coveragereport\Cobertura.xml'
    reportDirectory: 'coveragereport'
```
