### ISSUE TITLE
azuredevops: HtmlInline_AzurePipelines report type isn't using darktheme in Code Coverage tab

### ISSUE THREAD

**Issue by carlwoodhouse** [danielpalme/ReportGenerator#561]
Hi,

I have an azure devops pipeline that uses the marketplace extension

sample here:

```
   variables:
     disable.coverage.autogenerate: 'true'
   steps:
    - ${{ if ne(parameters.testCsProjPattern, '') }}:
      - task: DotNetCoreCLI@2
        displayName: "dotnet test"
        inputs:
          command: test
          projects: ${{ parameters.testCsProjPattern }}
          arguments: '--configuration Release --no-restore --collect "XPlat Code coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover'

      - task: reportgenerator@5
        displayName: 'merge code coverage reports'
        inputs:
          reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
          targetdir: '$(Pipeline.Workspace)/coverlet'
          reporttypes: HtmlInline_AzurePipelines;Cobertura
          verbosity: 'Verbose'

      - task: PublishCodeCoverageResults@1
        displayName: 'publish code coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(Pipeline.Workspace)/coverlet/Cobertura.xml'
          reportDirectory: '$(Pipeline.Workspace)/coverlet'
 ```

Not sure if im doing something wrong or a limitation but using this; the report shown in the 'Code Coverage' tab doesnt seem to adapt to the  darkmode theme. (if i download the report and open it it does)

sample output
![image](https://user-images.githubusercontent.com/465424/201980119-23fec374-ad8c-4e95-8a8c-687dba09b257.png)

**Comment by danielpalme** [comment]
When you download the report, the theme of your browser/operating system is picked up by the report.

When embedded into Azure DevOps this does not work. Azure DevOps has a separate setting for light/dark theme.

What you can do is use the reporttype `HtmlInline_AzurePipelines_Dark`:

```
      - task: reportgenerator@5
        displayName: 'merge code coverage reports'
        inputs:
          reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
          targetdir: '$(Pipeline.Workspace)/coverlet'
          reporttypes: HtmlInline_AzurePipelines_Dark;Cobertura
          verbosity: 'Verbose'
```

This will publish the dark version of the report.

Downside:
If other people will visit the "Code coverage" tab, they will also see the report in dark, even when they prefer the light theme.

Unfortunately there is no solution that works for everyone here.
