### ISSUE TITLE
[Question] Up-to-date overview: How to use ReportGenerator with Azure DevOps?

### ISSUE THREAD

**Issue by georg-jung** [danielpalme/ReportGenerator#646]
Thanks for creating ReportGenerator! I think it provides a great overview of code coverage and I really like all the integration options.

I got however a bit confused about all the options to use it and the best way to use ReportGenerator with Azure DevOps as of now, 2024. I've seen many issues discussing this topic including [#398](https://github.com/danielpalme/ReportGenerator/issues/398), but many of them are outdated as of 2024. Maybe it could be helpful for new users to have one central up-to-date page with guidance (which the other places including the Azure DevOps Marketplace page could link to). I'd be happy to contribute in that direction if that makes sense, but I guess at this point the best thing I can do is asking the questions I thought about when getting started with Code Coverage in Azure DevOps.

### My Goals (decreasing prio)

* having some working code coverage report at all
* having the "Code Coverage" tab with ReportGenerator's report, not the default one
* having a downloadable full-featured Code Coverage Report artifact
* short task runtime
* a quite general Azure Pipelines task definition that is easy to adapt to/copy around between multiple repos
* possibility to configure ReportGenerator, e.g. pass a license key
* having the "X.Y% covered" info on the "Summary" tab

### Options I came across

* PublishCodeCoverageResults@1
* PublishCodeCoverageResults@2
* reportgenerator@5
* A combination of the above

### What I think I understood

* Many shortcomings of PublishCodeCoverageResults are about V1. V2 made things better but there are even cases when one would rather use v1 than v2 (I'm not sure which exactly though).
* PublishCodeCoverageResults uses ReportGenerator under the hood. I think I didn't read it anywhere in docs/readme/website, but from reading the sources I understood that I could use a [`.netconfig file`](https://github.com/dotnetconfig/dotnet-config) to configure ReportGenerator while using PublishCodeCoverageResults@2 (maybe this should be documented somewhere, because I think it's a great feature). Mentioning how to use a ReportGenerator license with PublishCodeCoverageResults@2 on <https://reportgenerator.io/pro> would probably be easy and could even make some people buy a license (I tried this and it works).

### Questions

* Whats the minimal, optimal but full example to use ReportGenerator with Azure DevOps _today_? I've seen <https://reportgenerator.io/usage> but in my testing using only the `reportgenerator` task didn't produce e.g. the Code Coverage tab.

* Report type HtmlSummary sounds like it could help with <https://github.com/microsoft/azure-pipelines-tasks/issues/4945>, if it's acceptable to e.g. have just the summary in the "Code Coverage" tab but the full report in the zip artifact. Is there an easy way to set this up?

* `disable.coverage.autogenerate: 'true'` doesn't seem to work for me with `PublishCodeCoverageResults@2`. Is there a workaround for V2 too? Is it better to use V1 with `reportgenerator@5`?

* I have a DotNetCoreCLI@2 test task like the following. The PublishCodeCoverageResults@2 seems to first publish ReportGenerator's report, which is later overwritten. How to fix this while still publishing the trx test results?

```yaml
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(solution)'
    arguments: '--no-restore --configuration Release -s CodeCoverage.runsettings --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
    testRunTitle: 'release'
    publishTestResults: true
  displayName: dotnet test Release
```

* My current production pipeline config is similar to the following. It does fulfil most of my requirements except that the contents of "Code Coverage" are replaced by an autogenerated report when the pipleine finishes. How to get that right?

```yaml
variables:
  solution: './Xyz.sln'
  disable.coverage.autogenerate: 'true' # https://github.com/microsoft/azure-pipelines-tasks/issues/4945#issuecomment-823832527

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-22.04
    steps:
    - script: dotnet restore "$(solution)" /p:ContinuousIntegrationBuild=true
      displayName: dotnet restore

    - script: dotnet build --no-restore -c Release "$(solution)"  /p:ContinuousIntegrationBuild=true
      displayName: dotnet build

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '$(solution)'
        arguments: '--no-restore --configuration Debug -s CodeCoverage.runsettings --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
        testRunTitle: 'debug'
        publishTestResults: true
      displayName: dotnet test Debug

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '$(solution)'
        arguments: '--no-restore --configuration Release -s CodeCoverage.runsettings --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
        testRunTitle: 'release'
        publishTestResults: true
      displayName: dotnet test Release

    - task: PublishCodeCoverageResults@2
      displayName: 'Publish code coverage report'
      inputs:
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
        failIfCoverageEmpty: true
```

I hope I didn't miss any obvious places to research this myself. Thanks again for creating ReportGenerator!

**Comment by danielpalme** [comment]
Thanks for your detailed issue and the research behind it.

You are right, there are several options.
My experience is, that PublishCodeCoverageResults@1 or PublishCodeCoverageResults@2 are required to get the "Code Coverage" tab

PublishCodeCoverageResults@1 uses an (outdated) version of _ReportGenerator_ internally.
If you don't specify `disable.coverage.autogenerate: 'true'` it will (re-)generate the coverage report based on the Coberatura file.
If you want to use the latest version of _ReportGenerator_ you should always set `disable.coverage.autogenerate: 'true'`.

PublishCodeCoverageResults@2 does not use _ReportGenerator_ internally. If you have different information, I would be interested.  
Instead it generates it's own report which looks like this:
![image](https://github.com/danielpalme/ReportGenerator/assets/859606/9a5835a8-6f0c-4b33-9486-40c31c2eddd8)
As far as I know it's not possible to publish a full report with PublishCodeCoverageResults@2, since there is no `Report Directory` parameter.


**Regarding your questions**:
> - Whats the minimal, optimal but full example to use ReportGenerator with Azure DevOps today? I've seen https://reportgenerator.io/usage but in my testing using only the reportgenerator task didn't produce e.g. the Code Coverage tab.

Correct. You'll have to combine it with PublishCodeCoverageResults@1.
See also: https://github.com/danielpalme/ReportGenerator/wiki/Integration#azure-devops-extension


> - Report type HtmlSummary sounds like it could help with https://github.com/microsoft/azure-pipelines-tasks/issues/4945, if it's acceptable to e.g. have just the summary in the "Code Coverage" tab but the full report in the zip artifact. Is there an easy way to set this up?

You could generate two reports in separate directories. Then you would probably have to rename the `summary.html` file to `index.html` before publishing the it with PublishCodeCoverageResults@1

```yaml
- task: reportgenerator@5
  displayName: ReportGenerator
  inputs:
    reports: 'src\target\reports\coverage\coverage.xml'
    targetdir: '$(Build.SourcesDirectory)/coveragereport'
    reporttypes: 'HtmlInline_AzurePipelines;HtmlSummary;Cobertura'
    customSettings: 'settings:createSubdirectoryForAllReportTypes=true'

# Now rename file `$(Build.SourcesDirectory)/coveragereport/HtmlSummary/summary.html` to `$(Build.SourcesDirectory)/coveragereport/HtmlSummary/index.html`

# Create artifact of directory $(Build.SourcesDirectory)/coveragereport/HtmlInline_AzurePipelines

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coveragereport/Cobertura/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/coveragereport/HtmlSummary'
  env:
    DISABLE_COVERAGE_AUTOGENERATE: 'true'
```


> - disable.coverage.autogenerate: 'true' doesn't seem to work for me with PublishCodeCoverageResults@2. Is there a workaround for V2 too? Is it better to use V1 with reportgenerator@5?

As mentioned above, I'm pretty sure that you have to use PublishCodeCoverageResults@1.
`disable.coverage.autogenerate: 'true'` does not work here. And there is no option to specify a report directory any more. Am I missing something?!


> - I have a DotNetCoreCLI@2 test task like the following. The PublishCodeCoverageResults@2 seems to first publish ReportGenerator's report, which is later overwritten. How to fix this while still publishing the trx test results?

I guess that's not possible. See also your next question.


> - My current production pipeline config is similar to the following. It does fulfil most of my requirements except that the contents of "Code Coverage" are replaced by an autogenerated report when the pipleine finishes. How to get that right?

This is also my experience. See my answers above. I always use PublishCodeCoverageResults@1 instead of PublishCodeCoverageResults@2.

**Comment by georg-jung** [comment]
Thanks for your detailed response!

> PublishCodeCoverageResults@2 does not use ReportGenerator internally. If you have different information, I would be interested.

My example pipeline above with 

```yaml
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '$(solution)'
        arguments: '--no-restore --configuration Release -s CodeCoverage.runsettings --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
        testRunTitle: 'release'
        publishTestResults: true
      displayName: dotnet test Release

    - task: PublishCodeCoverageResults@2
      displayName: 'Publish code coverage report'
      inputs:
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
        failIfCoverageEmpty: true
```

\- and notably without any `reportgenerator@5` task - leads to the following behaviour:

* As soon as the `PublishCodeCoverageResults@2` task finished (but not the whole job/pipeline), the Code Coverage tab contains a ReportGenerator report. When specifying a license key using `.netconfig` it even contains a pro version report.
* At the same time, a "Code Coverage Report_<id>" artifact is created.
* As soon as the pipeline(/job?) finishes, the Code Coverage tab's content is _replaced_ with the report format that can be seen in your screenshot.
* The tasks log also contain lines like "Initializing report builders for report types: HtmlInline_AzurePipelines" that sound quite ReportGenerator related.
* In the end, I can view the `PublishCodeCoverageResults@2`-style report in the Code Coverage tab or download the ReportGenerator report from artifacts.

=> Thus, a V2 `disable.coverage.autogenerate: 'true'` might be quite interesting.

<https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines> reads

> #publishTestResults: true # boolean. Optional. Use when command = test. Publish test results *and code coverage*. Default: true.

Not sure how this might affect the behaviour.

I changed my pipeline now like this and it works as exected. The Code Coverage tab does contain the ReportGenerator report even after the end of the job (and also still accounts for `.netconfig`).

```yaml
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '$(solution)'
        arguments: '--no-restore --configuration Release -s CodeCoverage.runsettings --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
        testRunTitle: 'release'
        publishTestResults: true
      displayName: dotnet test Release

    # https://github.com/danielpalme/ReportGenerator/wiki/Integration#azure-devops-extension
    - task: reportgenerator@5
      displayName: '[Coverage] ReportGenerator'
      inputs:
        reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
        targetdir: '$(Agent.TempDirectory)/coveragereport'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
        assemblyfilters: '-xunit*'

    - task: PublishCodeCoverageResults@1
      displayName: '[Coverage] Publish results'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Agent.TempDirectory)/coveragereport/Cobertura.xml'
        reportDirectory: '$(Agent.TempDirectory)/coveragereport'
      env:
        DISABLE_COVERAGE_AUTOGENERATE: 'true'
```

Thanks for pointing me to <https://github.com/danielpalme/ReportGenerator/wiki/Integration#azure-devops-extension>. I actually overlooked this first (even though it's linked in the README 🙄 - I guess there are just many places providing pieces of information, some of which are more up to date while others aren't).

**Comment by danielpalme** [comment]
> => Thus, a V2 disable.coverage.autogenerate: 'true' might be quite interesting.

There is no such option. I looked at the source code: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV2

Internally `PublishCodeCoverageResults@1` uses https://github.com/microsoft/azure-pipelines-coveragepublisher to create the coverage reports.

**Comment by rikrak** [comment]
FWIW I would have benefitted from such a guide.  It took me some time to understand that the _PublishCodeCoverageResults@2_ task was flawed, and the older version is preferred in my scenario (which was similar to the one described above).  The main difficulty I faced in researching the production of a Devops Pipeline code coverage report, was that I didn't realise that a lot of the examples out in the wild (using the V2 task) are quite simplistic and don't cover what I'd consider a "real-world" scenario.  In addition I thought any examples using the older V1 task were out-of-date :-/

**Comment by danielpalme** [comment]
@rikrak 
Yes there are several options.

But the overall process is documented here:
https://github.com/danielpalme/ReportGenerator/wiki/Integration#azure-devops-vsts

The FAQs also answer the most common question:
https://github.com/danielpalme/ReportGenerator/wiki/FAQ#azure-devops-extension-seems-to-ignore-my-settings

**Comment by jchenathub24** [comment]
> * As soon as the `PublishCodeCoverageResults@2` task finished (but not the whole job/pipeline), the Code Coverage tab contains a ReportGenerator report. When specifying a license key using `.netconfig` it even contains a pro version report.
> * At the same time, a "Code Coverage Report_<id>" artifact is created.
> * As soon as the pipeline(/job?) finishes, the Code Coverage tab's content is _replaced_ with the report format that can be seen in your screenshot.

@georg-jung I come cross the same behaviour. 

When I test steps like:
1. dotnet test: generate coverage file
2. using PublishCodeCoverageResults@2

I can see that PublishCodeCoverageResults@2 internally use ReportGenerator, it shows a footer in the report saying that. But later, the whole report is override when pipeline finished. Feel like a bug for that task.

Also, I try the `disable.coverage.autogenerate: 'true'`, it does not change any outcome from PublishCodeCoverageResults@2

**Comment by danielpalme** [comment]
> Also wish there was `collapse all` & filter options in the report.

That's because Azure DevOps blocks all JavaScript.
If you download the full report artifact, those features will become available.

**Comment by cremor** [comment]
@danielpalme I think this issue should be reopened because the ReportGenerator documentation regarding Azure DevOps tasks should be updated. A few weeks ago Azure DevOps pipeline builds that use V1 of the PublishCodeCoverageResults tasks started showing deprecation warnings. See also the announcement here: https://devblogs.microsoft.com/devops/new-pccr-task/

Important part in that announcement:
> Q: I’m using Azure DevOps Server version 2022. What will happen to me?
A: In a future version of the Azure DevOps Server, we will also remove the V1 version of the publish code coverage results task. There will be a transitioning period where the V1 version will still run. During the transition period you’ll need to move from the V1 version to the V2 version, as when the transition period ends the V1 version will be removed and any pipeline containing that task will fail.

So there should be a documentation that shows how to correctly use ReportGenerator with PublishCodeCoverageResults V2.

**Comment by danielpalme** [comment]
@cremor 
I updated the documentation here:
https://github.com/danielpalme/ReportGenerator/wiki/Integration#attention

<br/>

> I think if you don't care how the HTML report looks and if you don't need to set any additional ReportGenerator settings, then you can simply use PublishCodeCoverageResults@2 now, without using reportgenerator@5 at all, because ReportGenerator will still be used to read/convert and merge the coverage reports.

The new version has several disadvantages regarding the report in the `Code Coverage` tab within Azure DevOps
- No branch and method coverage
- No details page for each class

**Comment by danielpalme** [comment]
I just released version 5.3.0 of _ReportGenerator_.

The _Azure DevOps_ task now has a new setting `publishCodeCoverageResults`.
This allows to publish the report in 'Code Coverage' tab directly. 
If set to true, it makes the 'PublishCodeCoverageResults' task(s) obsolete. They can be removed from your pipeline.

Example:
```yaml
- task: reportgenerator@5
  displayName: ReportGenerator
  inputs:
    reports: 'coverage.xml'
    targetdir: 'coveragereport'
    publishCodeCoverageResults: true
```

**Comment by MTomBosch** [comment]
When publishing the report "your way" is then still the html file regenerated from azure devops (which does not contain the branch and method coverage and details per class) or is your richer report uploaded?

**Comment by danielpalme** [comment]
@MTomBosch 
It's the richer report ([Sample report](https://reportgenerator.io/resources/reports/HtmlInline_AzurePipelines/index.html))

**Comment by cremor** [comment]
> The _Azure DevOps_ task now has a new setting `publishCodeCoverageResults`.
> This allows to publish the report in 'Code Coverage' tab directly.
> If set to true, it makes the 'PublishCodeCoverageResults' task(s) obsolete. They can be removed from your pipeline.

Thanks!
Does this also work with code coverage line indicators in pull requests?
I'd test it myself but TBH the feature seems to be flaky even with the official tasks 😅 

[Documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops)
Example when it works:
![grafik](https://github.com/danielpalme/ReportGenerator/assets/116314/13f0bdb9-1f39-4713-8c85-b68d42544c63)

**Comment by danielpalme** [comment]
@cremor 
> Does this also work with code coverage line indicators in pull requests?

I don't know. I have not tested this. Would like to hear if this also appears in PRs.

**Comment by A-Rai-col** [comment]
> > The _Azure DevOps_ task now has a new setting `publishCodeCoverageResults`.
> > This allows to publish the report in 'Code Coverage' tab directly.
> > If set to true, it makes the 'PublishCodeCoverageResults' task(s) obsolete. They can be removed from your pipeline.
> 
> Thanks! Does this also work with code coverage line indicators in pull requests? I'd test it myself but TBH the feature seems to be flaky even with the official tasks 😅
> 
> [Documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops) Example when it works: ![grafik](https://private-user-images.githubusercontent.com/116314/330712096-13f0bdb9-1f39-4713-8c85-b68d42544c63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTMwMDYsIm5iZiI6MTcxNTg1MjcwNiwicGF0aCI6Ii8xMTYzMTQvMzMwNzEyMDk2LTEzZjBiZGI5LTFmMzktNDcxMy04Yzg1LWI2OGQ0MjU0NGM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwOTQ1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGJhNWRlZDM4YzMzY2ExM2Q1YzQyMDMxOGNlZjg4NWUxNzc2MGFkZTNjZjk5ZDY4NDAxMDQ5Y2M5Nzg1NjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a2uJifewk3l2WCDrzhs_u2vjbrn0GxOk3RjtirI3mcQ)

Interesting. 
In the [ms docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops#which-coverage-tools-and-result-formats-can-be-used-for-validating-code-coverage-in-pull-requests)

>Which coverage tools and result formats can be used for validating code coverage in pull requests?
Code coverage for pull requests capability is currently only available for Visual Studio code coverage (.coverage) formats. This can be used if you publish code coverage using the Visual Studio Test task, the test verb of dotnet core task and the TRX option of the publish test results task. Support for other coverage tools and result formats will be added in future milestones.

They say it only supports `.coverage` formats though, so this will probably only work if you use the VSTest task.

**Comment by cremor** [comment]
> They say it only supports `.coverage` formats though

That's wrong or outdated. The screenshot I posted above is from a project that doesn't do anything with a .coverage file. At least not explicitly.
Here is the pipeline the project currently uses:

```yaml
  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      # Collect code coverage in OpenCover format because this is what SonarCloud supports.
      arguments: '--no-restore --configuration $(buildConfiguration) --collect:"XPlat Code Coverage;Format=opencover"'
      publishTestResults: true

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish code coverage report'
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.opencover.xml'
```

I'm planning of replacing `PublishCodeCoverageResults@2` with `reportgenerator@5`.

**Comment by A-Rai-col** [comment]
> ```yaml
>   - task: PublishCodeCoverageResults@2
>     displayName: 'Publish code coverage report'
>     inputs:
>       summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.opencover.xml'
> ```

I see, this might be an undisclosed feature they're adding the `PublishCodeCoverageResults@2` task.  💭 As neither the V2 task [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines) nor the [release notes](https://devblogs.microsoft.com/devops/new-pccr-task/) for it, has any mention code coverage for pull requests.

**Comment by cremor** [comment]
`PublishCodeCoverageResults@2` uses https://github.com/microsoft/azure-pipelines-coveragepublisher (which uses ReportGenerator.Core).
`reportgenerator@5` uses the same publishing method as `PublishCodeCoverageResults@1` used. I couldn't figure out where the source code of that is.

**Comment by cremor** [comment]
> I don't know. I have not tested this. Would like to hear if this also appears in PRs.

I can now answer this. Sadly PR line coverage does not show up with `reportgenerator@5` while it does work with `PublishCodeCoverageResults@2`. I don't know how `PublishCodeCoverageResults@2` does it but I assume it is something in https://github.com/microsoft/azure-pipelines-coveragepublisher

At least I know that it is **not** related to the files which are published as artifacts. Because currently `PublishCodeCoverageResults@2` doesn't publish any artifacts at all. Although that might be a bug, see microsoft/azure-pipelines-tasks#19547. Along with many other active issues for `PublishCodeCoverageResults@2`. It seems to be quite bad 😁

**Comment by A-Rai-col** [comment]
> I can now answer this. Sadly PR line coverage does not show up with `reportgenerator@5` while it does work with `PublishCodeCoverageResults@2`.


Still, cheers for sharing that something like code coverage for pull requests was a thing. That would be a very useful feature indeed. 
Hopefully, Microsoft eventually lets us publish ReportGenerator reports using `PublishCodeCoverageResults@2` task which **might** have that feature built in. 

Until then, thanks to @danielpalme we can now get rid of the deprecated warning that came with the V1 task. 🙌

**Comment by jasells** [comment]
OK, I just got caught up on this thread after finally getting the time to address the MS Publish code coverage results@v1 deprecation.  

@danielpalme   Been using this tool for year, such a great tool.

TY for adding the simple publish option in the latest of your ADO task, this solves the immediate issue of MS's deprecated publish coverage results task as well as the long-standing complicated config to publish the reports from your tool instead of the ADO-native reports.

Nothing like a forcing function to push progress!

To summarize this thread, [this post](https://github.com/danielpalme/ReportGenerator/issues/646#issuecomment-2110990308) shows how to publish _this_ tool's reports _directly_ to the Tests/Coverage tab in ADO without another "publish" task, MS or otherwise.

```
- task: reportgenerator@5
  displayName: ReportGenerator
  inputs:
    reports: 'coverage.xml'
    targetdir: 'coveragereport'
    publishCodeCoverageResults: true  << add this, remove MS' publish task V-any, no longer needed!
```

TY again!

@A-Rai-col 

I still get line coverage after only changing the publish option and removing MS's publish task entirely.  If it is missing, you may have your test step configured wrong.

 I use this package to generate the raw coverlet data, which this tool can then consume to create the reports.
 https://www.nuget.org/packages/coverlet.msbuild/6.0.2#show-readme-container
 
 Include it in all unit-test projects like:
 
 ```
 <PackageReference Include="coverlet.msbuild" Version="6.0.2" PrivateAssets="all">
 ```
 
 The step to run tests in my pipeline:
 
 ```
 dotnet test [unitTestProjectPath] --configuration "$(BuildConfiguration)" --logger "trx;" /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura%2copencover" /p:Exclude="[*Tests]*" /p:CopyLocalLockFileAssemblies=true
 ```
