### ISSUE TITLE
[Azure Devops] Combination of filefilters and sourcedirs filter out everything

### ISSUE THREAD

**Issue by Suchomel** [danielpalme/ReportGenerator#678]
I use `filefilters` and `sourcedirs` in same time, report is generated but all files are filtered out. When I use only `filefilters`, in summary is correctly filtered and on the detail is not visible covered lines. And when I use only `sourcedirs` the covered files are visible in the detail but of course files on summary are not filtered.

I use it for filter PR changed files in code coverage.

Yaml Pipeline:
```
          - task: Bash@3
            displayName: "Prepare variables"
            inputs:
              targetType: 'inline'
              script: |
                filefilters=$(git diff --name-only origin/"$TARGET_BRANCH_NAME" HEAD | grep '\.kt$' | sed 's|.*/||' | sed 's/^/+/' | tr '\n' ';')
                echo "##vso[task.setvariable variable=filefilters]$filefilters"
                sourcedirs=$(git diff --name-only origin/"$TARGET_BRANCH_NAME" HEAD | grep '\.kt$' | sed 's|/kotlin/.*$|/kotlin/|' | sed "s|^|$DEFAULT_WORKING_DIR/|g" | tr '\n' ';')
                echo "##vso[task.setvariable variable=sourcedirs]$sourcedirs"

          - task: reportgenerator@5
            displayName: "Code coverage report"
            inputs:
              reports: '$(System.DefaultWorkingDirectory)/android/library/code-coverage/build/reports/kover/report.xml;'
              filefilters: '$(filefilters)'
              sourcedirs: '$(sourcedirs)'
              reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
              publishCodeCoverageResults: true
```
