### ISSUE TITLE
How to get ReportGenerator working with azurepipelines-coverage.yml Pull Request commenting?

### ISSUE THREAD

**Issue by mahgo** [danielpalme/ReportGenerator#684]
I have an Azure Pipeline that currently publishes code coverage, via the following pipeline step:
```
- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage'
  inputs:
    summaryFileLocation: 'coverage/cobertura-coverage.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)'
    failIfCoverageEmpty: true'
```

I also have a `azurepipelines-coverage.yml` file in my repository: 
```
coverage:
  status:
    comments: on
    diff:
      target: 70%
```

This current setup adds a comment to the Azure Devops PRs - here is an example of how they might look:
![coveragedetailscomments](https://github.com/user-attachments/assets/505d6fb8-9032-4485-8f2b-8636fb994fc6)

However, when I replace PublishCodeCoverageResults@2 with the following, I no longer get the PR commenting anymore. How can I use ReportGenerator but still get this commenting? Here is the step now:
```
- task: reportgenerator@5
  displayName: Code coverage report
  inputs:
    reports: 'coverage/cobertura-coverage.xml'
    publishCodeCoverageResults: true
```

**Comment by mahgo** [comment]
Is it possible to use both PublishCodeCoverageResults@2 and reportgenerator@5, and have the pipeline show the reportgenerator report then?

**Comment by danielpalme** [comment]
Maybe this works. I haven't tried that yet.
Probably reportgenerator should be the last step to overwrite the report of PublishCodeCoverageResults@2.

**Comment by mahgo** [comment]
It looks like when I use both `PublishTestResults@2` and `reportgenerator@5`, regardless of the order, the `PublishTestResults@2` report is the one that shows up under "Code Coverage" on the pipeline, do you have any suggestions for how the report could be overridden?

**Comment by danielpalme** [comment]
I'm sorry but I don't know if it there is an option to overwrite the report.

**Comment by erenken** [comment]
I would love this functionailty as well.  I am trying some options in the report generation

HtmlInline_AzurePipelines_Dark;Cobertura;OpenCover

That didn't work.  I think the azurepipelines-coverage.yml needs the .coverage file but I don't think that is being generated.

**Comment by sj-net** [comment]
I needed this functionality very badly as many of our projects were using PR Code Coverage Check and didn't want to remove that just because the HTML reports are great by this tool. So how about adding the report generated by reportgenerator to a new tab with some custom name of user choice ? Ex: [Sarif](https://marketplace.visualstudio.com/items?itemName=sariftools.scans) adds a new tab for its report.

**Comment by danielpalme** [comment]
@sj-net 
You can publish the report in a separate tab with this extension:

```yaml
- task: JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport@1
  displayName: "Publish code coverage report"
  inputs:
    reportDir: '$(Build.SourcesDirectory)/coveragereport/index.html'
    tabName: 'Code Coverage (Complete)'
```

See also: https://marketplace.visualstudio.com/items?itemName=JakubRumpca.azure-pipelines-html-report
