### ISSUE TITLE
Latest release 5.4.0 does not exclude files where it did before this version

### ISSUE THREAD

**Issue by JeroenJSmit** [danielpalme/ReportGenerator#707]
**Describe the bug**
We have been excluding generated function app (C#) code from the test coverage results successfully until the latest version 5.4.0 which states it actually fixes that but seems to break it.

**To Reproduce**
We call the report generator tool in a DevOps pipeline using the following script

```
  - script: >-
      reportgenerator
      -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml
      -targetdir:$(Build.SourcesDirectory)/coverlet/reports
      -assemblyfilters:+*;-*.*.Tests
      -filefilters:+*;-*.g.cs
      -reporttypes:"Cobertura"
    displayName: Generate Coverage Reports
```

The relevant part is the filefilters excluding "*.g.cs".

Since this morning the reported coverage in our pipelines dropped with about 7%.
Tested using version 5.3.11 explicitly (previous version) and the coverage went back to what it was yesterday (so +7%).

From the documentation I do not see a change in how I should pass in the excluded files with a wildcard, so this feels like a regression to me.

**Comment by TobiasLoeschVolue** [comment]
Same here. With the latest version `5.4.0` some of our test files are no longer excluded, the configuration for the GitHub-Action is unchanged.
```
- name: Generate coverage report
      if: ${{ github.triggering_actor != 'dependabot[bot]' }}
      uses: danielpalme/ReportGenerator-GitHub-Action@v5.4.0
      with:
        reports: ./src/TestResults/*/coverage.cobertura.xml
        targetdir: coveragereport
        sourcedirs: ./src
        reporttypes: 'MarkdownSummaryGithub;Cobertura'
        verbosity: Info
        toolpath: reportgeneratortool
        assemblyfilters: '-*.Tests.dll'
        filefilters: '-*M7Schema.V*.cs;-*Tests.cs;-*.g.cs'
```
