### ISSUE TITLE
Azure Pipeline Report Generator display less information on Cobertura MultiReport

### ISSUE THREAD

**Issue by PyHahiro** [danielpalme/ReportGenerator#722]
**Describe the bug**
Hello, I have a csharp multi-project private repository, and I am using Azure Pipelines in order to integrate Code Coverage to my ci/cd objectives
I have a VsTest task that produces x4 cobertura.xml. Here are few logs indicating what is hapenning in VsTest first :  

```
Fichier de résultats : <private-agent>\TestResults\vm-buildms-dev-$_vm-buildms-dev-_2025-01-29_10_14_31.trx
Pièces jointes :
  <private-agent>\TestResults\7a37783f-b7f0-4b61-83f8-e48c3e73621b\coverage.cobertura.xml
  <private-agent>\TestResults\7621bd7a-9da8-4fdb-9b1d-ce55da77bda7\coverage.cobertura.xml
  <private-agent>\TestResults\0aae359f-8ab9-4133-9464-797432c95feb\coverage.cobertura.xml
  <private-agent>\TestResults\053a23bb-c5e8-4e68-a8ff-a660244c8bd3\coverage.cobertura.xml
Série de tests réussie.
Nombre total de tests : 49
     Réussi(s) : 49
 Durée totale : 23,9589 Secondes
```
Which then, using Report Generator publishes the following :  
```
Reading code coverage summary from '<private-agent>\CoverageResults/Cobertura.xml'
Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Lines- 49 of 11146 covered.
 Branches- 7 of 3480 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 296 files
Total file: 296 ---- Processed file: 49 (16%)
Total file: 296 ---- Processed file: 145 (48%)
Total file: 296 ---- Processed file: 258 (87%)
File upload succeed.
Published <private-agent>\CoverageResults' as artifact 'Code Coverage Report_202978'
Async Command End: Publish code coverage
```

You can then see that it is working as intended 
Bellow is my ReportGenerator Pipeline configuration and the result

```yml
steps:
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@5
  displayName: 'Format and Merge code coverage files'
  inputs:
    reports: '$(Build.SourcesDirectory)/TestResults/*/*.cobertura.xml;'
    targetdir: '$(Build.SourcesDirectory)/CoverageResults'
    reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura;Badges'
    publishCodeCoverageResults: true
```
![Image](https://github.com/user-attachments/assets/29c370a5-f9b6-449e-bbbc-dcb93e3ccfa1)

**But then**, I added more test in another branch and ran the same pipeline, which did not change anything in the report.

So I decided to remove every other cobertura.xml files and tweak some parameters to only generate *one* file for one specific project, the project I had added new tests, and here were my ReportGenerator logs and results

```
Reading code coverage summary from '<private-agent>\CoverageResults/Cobertura.xml'
Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Lines- 184 of 26787 covered.
 Branches- 43 of 10722 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 560 files
Total file: 560 ---- Processed file: 33 (5%)
Total file: 560 ---- Processed file: 133 (23%)
Total file: 560 ---- Processed file: 241 (43%)
Total file: 560 ---- Processed file: 341 (60%)
Total file: 560 ---- Processed file: 448 (80%)
Total file: 560 ---- Processed file: 555 (99%)
File upload succeed.
Published '<private-agent>\CoverageResults' as artifact 'Code Coverage Report_202985'
Async Command End: Publish code coverage
```

![Image](https://github.com/user-attachments/assets/f2661f04-d60b-41f7-8b83-55fecacbcdc7)

Which is worrying to me because, not only that one generated cobertura.xml have more information, but it has a broader range of assemblies, the only plausible answer that comes to mind, is that the file merging **only** includes shared assemblies, which would defeat the purpose as, in my cases, would only produce code coverage for code under a `Common` label

Additional information : 
- I ran the pipeline with both free version 4 and 5 available in Azure Devops
- I ran the pipeline on the same branch that added tests with the same changes.
- In my MultiReport, there are no files of other projects than a `Common` shared amongst all my built test projects

Here is a snippet of yaml of my VsTest pipeline job :  
```yaml
steps:
- task: VSTest@3
  displayName: 'Vstest Unit Testing'
  inputs:
    azureSubscription: <privateAzureSubscription>
    testAssemblyVer2: '$(system.defaultworkingdirectory)\<private-project-path>\bin\Release\net8**\*.Test.*.dll'
    searchFolder: '$(Build.SourcesDirectory)'
    resultsFolder: '$(Build.SourcesDirectory)\TestResults'
    runOnlyImpactedTests: false
    vsTestVersion: 17.0
    runInParallel: false
    codeCoverageEnabled: true
    otherConsoleOptions: '/Collect:"XPlat Code Coverage" /TestAdapterPath:$(system.defaultworkingdirectory)\_alpha_\packages\coverlet.collector\6.0.4\build\netstandard2.0'
```
I also tried using VSTest@2 with the same results
